name: Docker Image CI

on:
  push:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          # Username used to log against the Docker registry
          username: larsbauer91
          # Password or personal access token used to log against the Docker registry
          password: ${{ DOCKER_ACCESS_TOKEN }}
          # Log out from the Docker registry at the end of a job
          logout: true
      
